language: node_js
node_js:
  - "lts/*"
install:
  - npm ci
  - ls
  - cd ./backend
  - ls
  - npm ci
  - ls
  - cd ../frontend
  - ls
  - npm ci
  - ls
  - cd ..
cache:
  directories:
  - "$HOME/.npm"
script:
  - npm run lint
  - ls