language: node_js
node_js:
  - "lts/*"
cache:
  directories:
  - "$HOME/.npm"
matrix:
  fast_finish: true
  include:
    - stage: root
      install:
        - npm ci
    - stage: backend
      install:
        - cd ./backend
        - npm ci
    - stage: frontend
      install:
        - cd ./frontend
        - npm ci

script:
  - npm run lint
on: 
  branch: main