language: node_js
node_js:
  - "lts/*"
cache:
  directories:
  - "$HOME/.npm"
jobs:
  fast_finish: true
  include:
    - stage: root
      install:
        - npm ci
    - stage: backend
      install:
        - cd ./backend
        - npm ci
    - stage: frontend
      install:
        - cd ./frontend
        - npm ci
    - stage: Run Linter
      before_install:
        - cd ./backend
        - npm ci
        - cd ../frontend
        - npm ci
        - cd ..
      install:
        - npm ci
      script:
        - npm run lint
    - stage: Run Tests
      before_install:
        - cd ./backend
        - npm ci
        - cd ..
      install:
        - npm ci
      script:
        - cd ./backend
        - docker-compose build
        - docker-compose up -d
        - cd ..
        - sleep 15
        - npm run test